// <auto-generated />
namespace WebAppSample0250606.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addUserTable1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserTable1));
        
        string IMigrationMetadata.Id
        {
            get { return "202506092112413_addUserTable1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
